# WorldwideChat Configuration
#       _    _            _     _          _     _      _____ _           _   
#      | |  | |          | |   | |        (_)   | |    /  __ \ |         | |  
#      | |  | | ___  _ __| | __| |_      ___  __| | ___| /  \/ |__   __ _| |_ 
#      | |/\| |/ _ \| '__| |/ _` \ \ /\ / / |/ _` |/ _ \ |   | '_ \ / _` | __|    - by BadSkater0729
#      \  /\  / (_) | |  | | (_| |\ V  V /| | (_| |  __/ \__/\ | | | (_| | |_ 
#       \/  \/ \___/|_|  |_|\__,_| \_/\_/ |_|\__,_|\___|\____/_| |_|\__,_|\__|
#
# HOW TO SETUP: https://github.com/BadSkater0729/WorldwideChat/wiki/Default-Explained-config.yml
#
General:
  prefixName: WWC
  enablebStats: true
  pluginLang: en
  updateCheckerDelay: 86400
  syncUserDataDelay: 7200
  fatalAsyncTaskTimeout: 10
  enableDebugMode: false
Storage:
  useSQL: false
  sqlHostname: localhost
  sqlPort: 3306
  sqlDatabaseName: cooldatabase
  sqlUsername: root
  sqlPassword: root
  sqlUseSSL: false
  sqlOptionalArgs: []
  useMongoDB: false
  mongoHostname: localhost
  mongoPort: 27017
  mongoDatabaseName: cooldatabase
  mongoUsername: admin
  mongoPassword: password
  mongoOptionalArgs: []
Chat:
  sendTranslationChat: true
  sendPluginUpdateChat: true
  sendIncomingHoverTextChat: true
Translator:
  useWatsonTranslate: true
  watsonAPIKey: watson_key_goes_here
  watsonURL: watson_site_goes_here
  useGoogleTranslate: false
  googleTranslateAPIKey: google_translate_key_goes_here
  useAmazonTranslate: false
  amazonAccessKey: amazon_translate_key_goes_here
  amazonSecretKey: amazon_translate_secret_goes_here
  amazonRegion: amazon_region_goes_here
  useLibreTranslate: false
  libreAPIKey: none
  libreURL: libre_url_goes_here
  useDeepLTranslate: false
  deepLAPIKey: deepl_key_goes_here
  useAzureTranslate: false
  azureAPIKey: azure_key_goes_here
  azureRegion: azure_region_goes_here
  useSystranTranslate: false
  systranAPIKey: systran_key_goes_here
  translatorCacheSize: 100
  rateLimit: 0
  messageCharLimit: 255
  errorLimit: 5
  errorsToIgnore:
  - "confidence"
  - "same as target"
  - "detect the source language"
  - "Unable to find model for specified languages"
